// Code generated by clipper. DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

var greetCmd *cobra.Command

type Service interface {
	Greet(cmd *cobra.Command, args []string)
}

func NewGreetCmd(svc Service) *cobra.Command {
	greetCmd = &cobra.Command{
		Use:   "greet",
		Short: "fight the loneliness!",
		Long:  `fight the loneliness!`,
		Run: func(cmd *cobra.Command, args []string) {
			svc.Greet(cmd, args)
		},
	}
	return greetCmd
}

func Execute(svc Service) {
	NewGreetCmd(svc)
	addCommands(svc)
	err := greetCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func addCommands(svc Service) {
}
