// Code generated by clipper. DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
)

var addCmd *cobra.Command

func NewAddCmd(svc Service) *cobra.Command {
	addCmd = &cobra.Command{
		Use:   "add",
		Short: "add a task to the list",
		Long:  ``,
		Run: func(cmd *cobra.Command, args []string) {
			svc.Add(cmd, args)
		},
	}
	return addCmd
}
