// Code generated by clipper. DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
)

var completeCmd *cobra.Command

func NewCompleteCmd(svc Service) *cobra.Command {
	completeCmd = &cobra.Command{
		Use:   "complete",
		Short: "complete a task on the list",
		Long:  `complete a task on the long list`,
		Run: func(cmd *cobra.Command, args []string) {
			svc.Complete(cmd, args)
		},
	}
	return completeCmd
}
