// Code generated by clipper. DO NOT EDIT.
package cmd

import (
	"os"

	"github.com/spf13/cobra"
)

var subcommandManagerCmd *cobra.Command

type Service interface {
	Add(cmd *cobra.Command, args []string)
	Complete(cmd *cobra.Command, args []string)
	TemplateAdd(cmd *cobra.Command, args []string)
	TemplateRemove(cmd *cobra.Command, args []string)
}

func NewSubcommandManagerCmd(svc Service) *cobra.Command {
	subcommandManagerCmd = &cobra.Command{
		Use:   "subcommmand-manager",
		Short: "fight the loneliness!",
		Long:  `fight the loneliness!`,
	}
	return subcommandManagerCmd
}

func Execute(svc Service) {
	NewSubcommandManagerCmd(svc)
	addCommands(svc)
	err := subcommandManagerCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

func addCommands(svc Service) {
	subcommandManagerCmd.AddCommand(NewAddCmd(svc))
	subcommandManagerCmd.AddCommand(NewCompleteCmd(svc))
	subcommandManagerCmd.AddCommand(NewTemplateCmd(svc))
	templateCmd.AddCommand(NewTemplateAddCmd(svc))
	templateCmd.AddCommand(NewTemplateRemoveCmd(svc))
}
