// Code generated by clipper. DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
)

var templateRemoveCmd *cobra.Command

func NewTemplateRemoveCmd(svc Service) *cobra.Command {
	templateRemoveCmd = &cobra.Command{
		Use:   "remove",
		Short: "remove an existing template",
		Long:  ``,
		Run: func(cmd *cobra.Command, args []string) {
			svc.TemplateRemove(cmd, args)
		},
	}
	return templateRemoveCmd
}
